##################################################################################################################################
#                                                                                                                                #
# How to run me ?                                                                                                                #
# ansible-playbook -i '127.0.0.1,' scan_python_files.yaml --extra-vars 'Remote_Host_Pass=redacted Local_Sudo_Pass=redacted'      #
#                                                                                                                                #
##################################################################################################################################
-
  hosts:  all
  gather_facts: yes
  any_errors_fatal: true
  become: true


  roles:
    - scan_python_files