---

#We are assigning the sudo seperately for local and remote host, As it may be different in certain scenario's.


- name: Storing local sudo password in memory.
  set_fact:
    ansible_become_pass: "{{ local_sudo_pass }}"
  delegate_to: "{{ local_vm_hostname }}"
  delegate_facts: True
  register: set_sudo_pass_local_result
  tags:
    - set_sudo_pass_local
    - always

- debug:
    msg: " Sudo password for local machine is cached in memory"
  tags:
    - always
    - set_sudo_pass_local
  when: set_sudo_pass_local_result is defined

- name: Check local directory to store reports is present or not.
  stat:
    path: "{{ local_report_directory }}"
  register: check_local_report_directory_stat_result
  tags:
    - check_local_report_directory_stat

- debug:
    msg:
      - "Local storage directory check task output {{ check_local_report_directory_stat_result }}"
      - "Local storage directory check task output {{ check_local_report_directory_stat_result.changed }}"
  when: check_local_report_directory_stat_result is defined
  tags:
    - check_local_report_directory_stat

- name: Creating a directory in local to store all the data.
  file:
    path: "{{ local_report_directory }}"
    state: directory
    owner: ansible
    group: ansible
    mode: '0700'
  delegate_to: localhost
  register: create_folder_for_local_report_storage_result
  when: check_local_report_directory_stat_result.stat.isdir is not defined
  tags:
    - create_folder_for_local_report_storage

- debug:
    msg:
      - "Creating folder for storing data in local task output - {{ create_folder_for_local_report_storage_result }}"
      - "Creating folder for storing data in local task status - {{ create_folder_for_local_report_storage_result.changed }}"
  when: Create_folder_for_local_Report_Storage_Result is defined
  tags:
    - create_folder_for_local_report_storage

- name: Creating a directory inside /tmp to store the session data.
  file:
    path: "{{ item }}"
    state: directory
    owner: ansible
    group: ansible
    mode: '0700'
    recurse: yes
  with_items:
    - "{{ required_folder_var }}"
    - "{{ required_folder_var + remote_report_directory }}"
  register: create_folder_for_session_data_result
  tags:
    - create_folder_for_session_data

- debug:
    msg:
      - "Creating folder for storing session data task output - {{ create_folder_for_session_data_result }}"
      - "Creating folder for storing session data task output status - {{ create_folder_for_session_data_result.changed }}"
  when: create_folder_for_session_data_result is defined
  tags:
    - create_folder_for_session_data

- name: Installing Bandit using PIP.
  pip:
    name: Bandit
  register: install_bandit_result
  tags:
    - install_bandit
- debug:
    msg:
      - "Installing Bandit task output {{ install_bandit_result }}"
      - "Installing Bandit task status - {{ install_bandit_result.changed }}"
  when: install_bandit_result is defined
  tags:
    - install_bandit

- name: Copying scan_python_files.py file.
  synchronize:
    src: bandit_python_scanner_script
    dest: "{{ required_folder_var }}"
    mode: push
  become: False
  register: copy_scan_using_bandit_python_result
  tags:
    - copy_scan_using_bandit_python

- debug:
    msg:
      - "Copying scanning script task output {{ copy_scan_using_bandit_python_result }}"
      - "Copying scanning script task Status - {{ copy_scan_using_bandit_python_result.changed }}"
  when: copy_scan_using_bandit_python_result is defined
  tags:
    - copy_scan_using_bandit_python

- name: Running static code analysis for the python files running on the host.
  shell: python scan_python_files.py --outputfolder "{{ required_folder_var + remote_report_directory }}" --sudopassword "{{ ansible_become_pass }}"
  args:
    chdir: "{{ required_folder_var + bandit_python_scriptdir }}"
  become: true
  when: create_folder_for_session_data_result.results[0].failed == False
  register: run_bandit_code_analysis_result
  tags:
    - run_bandit_code_analysis

- debug:
    msg:
      - "Code analysis for python files task output - {{ run_bandit_code_analysis_result.stdout }}"
      - "Code analysis for python files task status - {{ run_bandit_code_analysis_result.changed }}"
  when: run_bandit_code_analysis_result is defined
  tags:
    - run_bandit_code_analysis

- name: Change permission for report files.
  file:
    path: "{{ required_folder_var + remote_report_directory }}"
    state: directory
    owner: ansible
    group: ansible
    recurse: yes
  register: change_reports_permission_result
  when: run_bandit_code_analysis_result is defined
  tags:
    - change_reports_permission

- debug:
    msg:
      - "Change permission for report file task output {{  change_reports_permission_result }}"
      - "Change permission for report file task Status {{  change_reports_permission_result.changed }}"
  when: change_reports_permission_result
  tags:
    - change_reports_permission

- name: Copying the report files from remote host to ansible server.
  synchronize:
    src: "{{ required_folder_var + remote_report_directory }}"
    dest: "{{ local_report_directory }}"
    mode: pull
  become: False
  register: copy_reports_to_local_result
  tags:
    - copy_reports_to_local

- debug:
    msg:
      - "Copying Reports to ansible server task output {{ copy_reports_to_local_result }}"
      - "Copying Reports to ansible server task status -  {{ copy_reports_to_local_result.changed }}"
  when: copy_reports_to_local_result
  tags:
    - copy_reports_to_local